### ISSUE TITLE
Integrate Power BI Report Sheet in existing BI Report

### ISSUE THREAD

**Issue by Elmar83** [ben-howard/PowerBI-Planner#5]
Hello Ben,

First of all I have to say that I'm very impressed on the Power BI Template you build for the Planner.
It shows exactly the data that I wanted.

Unfortunatly, I have already build a report in order to get a overview of numerous strategic projects and their status.

Now I would like to integrate one of your Power Bi Report Sheets into my already existing report.

Do you know a way, how to do this?

Best Regards,

Elmar

**Comment by ben-howard** [comment]
Hi Elmar,

Thank you for the feedback on my planner report.  It’s impossible to say how easy/difficult it would be to integrate two reports together without seeing them both side by side.

From: Elmar83 ***@***.***>
Sent: 13 April 2021 19:52
To: ben-howard/PowerBI-Planner ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ben-howard/PowerBI-Planner] Integrate Power BI Report Sheet in existing BI Report (#5)


Hello Ben,

First of all I have to say that I'm very impressed on the Power BI Template you build for the Planner.
It shows exactly the data that I wanted.

Unfortunatly, I have already build a report in order to get a overview of numerous strategic projects and their status.

Now I would like to integrate one of your Power Bi Report Sheets into my already existing report.

Do you know a way, how to do this?

Best Regards,

Elmar
